name: mandiri_pbb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  animated_toggle_switch: ^0.8.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_native_splash: 
  android: true 
  ios: true 
  web: true 
  color: "#578b98" 
  image: "assets/images/PIL EMAS.png"
